/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package BreveCreatures;

import BaseObjects.Chromosome;
import BaseObjects.VariableLengthChromosome;
import GeneticAlgorithm.GeneticAlgorithm;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Seva
 */
public class FileBrowser extends javax.swing.JFrame {

    /**
     * Creates new form FileBrowser
     */
    private File currFile;
    private ArrayList<Chromosome> toSave = new ArrayList<>();
    private BreveKnockOff overlord;

    public FileBrowser(BreveKnockOff overlord) {
        this.overlord = overlord;
        initComponents();
        FileNameExtensionFilter f = new FileNameExtensionFilter("Genetic Algorithm Lists", "list");
        this.fileChooser.setFileFilter(f);
    }

    public File getSelectedFile() {
        return currFile;
    }

    public void setSelectedFile(String in) {
        this.fileChooser.setSelectedFile(new File(in + ".list"));
    }

    public void setList(ArrayList<Chromosome> in) {
        toSave = in;
    }

    public ArrayList<Chromosome> getList() {
        return toSave;
    }

    public void setCommandButton(String in) {
        this.fileChooser.setApproveButtonText(in);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fileChooser.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        fileChooser.setApproveButtonText("Select");
        fileChooser.setApproveButtonToolTipText("");
        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\Seva\\Documents\\NetBeansProjects\\Genetics"));
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            switch (this.fileChooser.getApproveButtonText()) {
                case "Save":
                    currFile = this.fileChooser.getSelectedFile();
                    System.out.println("Saving " + currFile.getName());
                    try {
                        ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(currFile.getName()));
                        out.writeObject(toSave);
                        out.flush();
                    } catch (Exception e) {
                        e.printStackTrace(System.err);
                    }
                    this.setVisible(false);
                    break;
                case "Load":
                    currFile = this.fileChooser.getSelectedFile();
                    System.out.println("Loading " + currFile.getName());
                    try {
                        ArrayList<Chromosome> temp = (ArrayList<Chromosome>) (new ObjectInputStream(new FileInputStream(currFile.getName()))).readObject();
                        //System.out.println(temp);
                        System.out.println(temp.get(0));
                        System.out.println(temp.get(0).getInputs());
                        overlord.ga = new GeneticAlgorithm(temp, temp.get(0) instanceof VariableLengthChromosome, temp.get(0).getInputs());
                    } catch (IOException | ClassNotFoundException ex) {
                        ex.printStackTrace(System.err);
                    }
                    this.setVisible(false);
                    break;
            }
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_fileChooserActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
